[package]
name = "riirando-common"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = "2.0.66"
